version: '3.8'

volumes:
  movies_volume_mongo:

networks:
  movies_network:
    driver: bridge

services:
  web:
    image: gfagundes/rotten_potatoes:v1
    ports:
      - 5000:5000
    networks:
      - movies_network
    depends_on:
      - mongodb_movies
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb_movies
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd

  mongodb_movies:
    image: mongo:5.0.6
    networks:
      - movies_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    volumes:
      - movies_volume_mongo:/data/db 